static void wifi_event_handler(void *event_handler_arg, esp_event_base_t event_base, int32_t event_id, void *event_data);
void wifi_connection();
void shiftOut(uint8_t bits);
void initialize_gpio_for_SR();
void IRAM_ATTR gpio_isr_handler(void* arg);
void initialize_gpio_for_PIR();
void setLEDRange(int left, int right);
void checkToTurnOnLEDsFromWebSocket(esp_websocket_event_data_t *data);
void checkToTurnOnMotorsFromWebSocket(esp_websocket_event_data_t *data);
static void on_websocket_event(void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data);
static void ws_client_task(void *pvParameters);
void setupStepperDriverPins();
void stepper(void *pvParameters);
void init_motor_right();
void init_motor_left();
void move(int motor, int speed, int direction);
void stop();
void start();
void moveForward();
void moveLeft();
void moveRight();
void move180();
void app_main(void);